# Generated by Django 5.1.1 on 2024-10-14 06:28

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mediku',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('espezializazioa', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Paziente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('izena', models.CharField(max_length=75)),
                ('abizena', models.CharField(max_length=100)),
                ('jaiotze_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('emaila', models.CharField(max_length=100)),
                ('mugikorra', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Zita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zita_data', models.DateTimeField(default=django.utils.timezone.now)),
                ('oharra', models.CharField(max_length=100)),
                ('medikua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osakidetza.mediku')),
                ('pazientea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='osakidetza.paziente')),
            ],
        ),
    ]
